import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  {
    rules: {
      // Unused args are fine when prefixed with `_` (common in handlers).
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "warn",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      // `process.env` bypasses the validated `env` module.
      "no-restricted-properties": [
        "error",
        {
          object: "process",
          property: "env",
          message:
            "Import `env` from '@/env' instead so missing variables fail at build time.",
        },
      ],
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },

  // Infrastructure files legitimately read raw process.env before validation.
  {
    files: [
      "src/env.ts",
      "src/lib/logger.ts",
      "src/instrumentation.ts",
      "src/proxy.ts",
      "*.config.ts",
      "*.config.mjs",
      "e2e/**",
    ],
    rules: { "no-restricted-properties": "off", "no-console": "off" },
  },

  // Generated by the shadcn CLI — keep diffs clean when components are re-added.
  {
    files: ["src/components/ui/**"],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },

  // Must come last so formatting rules never fight Prettier.
  prettier,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
